### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by martinkeat** [burst-apps-team/burstpool#1]
Hey Harry,

Is there any deployment instructions for this. Im a noob just doing it for the learning experience. Would love to deploy this and give it a whurl.

**Comment by harryjph** [comment]
Hi there!

Hi, sorry for the slow reply. If you want to deploy you need to grab 3 files:

`pool.properties` from the source code root

`log4j2.xml` from the releases page

`burstcoin-pool-all.jar` from the releases page

You then need to place all of these files in the same directory and modify `pool.properties` to suit your pool setup. Then, in order to run the pool, run the command:

`java -Dlog4j.configurationFile=log4j2.xml -jar burstcoin-pool-all.jar`

**Comment by martinkeat** [comment]
Recommended server specs?

**Comment by harryjph** [comment]
Not really sure how much it needs, probably not a lot..

Current testnet server is 4 cores, 8GB ram in order to run both a full node and the pool

**Comment by martinkeat** [comment]
Where can i find demo?

**Comment by harryjph** [comment]
http://75.100.126.230:8124/index.html

**Comment by wy414012** [comment]
Hello, I am a novice, can you provide a complete deployment process for learning?

**Comment by shefass** [comment]
Sorry but no, don't "steal" harry:) He is very important to us

2019-06-16, sk, 10:02 wy414012 <notifications@github.com> rašė:

**Comment by wy414012** [comment]
Well, thank you.

**Comment by harryjph** [comment]
@wy414012 yes. I will do a write up of how to deploy.

**Comment by harryjph** [comment]
@wy414012 https://github.com/burst-apps-team/burstpool/issues/25

**Comment by wolfduan** [comment]
I found some ming pool have total capacity for burst network?How did them calculated the total capacity?

**Comment by wolfduan** [comment]
@harry1453

**Comment by harryjph** [comment]
Total capacity = genesis base target / base target

genesis base target = 4398046511104 / 240

**Comment by wolfduan** [comment]
> Total capacity = genesis base target / base target
> 
> genesis base target = 4398046511104 / 240

Can you tell me why we can get the total capacity in this way?

**Comment by harryjph** [comment]
This post contains an explanation: https://www.reddit.com/r/burstcoin/comments/akbxcy/genesis_base_target_bhd_capacity_estimates/
