### ISSUE TITLE
Frontend plans, api

### ISSUE THREAD

**Issue by shefass** [burst-apps-team/burstpool#2]
Hi,

I am now learning react and started to do React Native apps (lunched only one :) ). I am planing to specialize myself at this direction. Do you planing to do back-end which accepts api calls and gives replays, so others can build on top of this front ends? I am interesting in writing app(android/iOS), which monitors you miner at pool. Please share you plans.

Thank your for your work

**Comment by harryjph** [comment]
Hi, there are currently 3 API endpoints:

`api/getMiners`: Returns an array of all miners

`api/getMiner/{address}`: Returns a miner

`api/getConfig`: Returns pool configuration

I haven't had the time to document these but you should be able to figure them out by poking them on the test pool. All of them use GET and respond in JSON.
