### ISSUE TITLE
According to your source code compilation and release found a problem capacity statistics has been 0.0TB show bugs?

### ISSUE THREAD

**Issue by wy414012** [burst-apps-team/burstpool#33]
According to your source code compilation and release found a problem capacity statistics has been 0.0TB show bugs?

**Comment by harryjph** [comment]
I'm sorry? The capacity estimation is not working?

If so, please wait at least `processLag` blocks before the capacity will slowly start to rise. It will be accurate after `processLag + nAvg` blocks.

**Comment by wy414012** [comment]
Maybe there is something wrong with the way I deploy it. There are two known problems. There is no statistics on the winners and the capacity has not been shown. @

**Comment by wy414012** [comment]
Test Deployment Address     http://burst.qicp.vip:8124/index.html    @harry1453

**Comment by harryjph** [comment]
You may need to fast forward the block processing. This will be automatic in the next version.

1. Shutdown pool

2. Execute SQL https://pastebin.com/NFqGJbpW

3. Start pool

4. Wait. Capacity should start to show shortly.

**Comment by harryjph** [comment]
For future reference, this process is automatic starting from v1.1.0
